# Global Settings
settings:
  # PREMIUM OPTIMIZATION: Chunk-based Lookups (Spatial Hashing)
  # Highly recommended for servers with 20+ mines or explosive pickaxe enchants.
  use-spatial-hashing: true

  # How long should a chat prompt stay open before timing out and preventing memory leaks? (In seconds)
  chat-prompt-timeout: 60

  # Pagination limits for commands/GUIs (Maximum items displayed per page)
  stats-per-page: 10
  timers-per-page: 10
  help-per-page: 10
  warps-per-page: 45

  # The hourly offset from your server's system time for scheduled cron resets.
  timezone-offset: 0

  skip-empty-resets: true
  schematic-placeholder-block: "SPONGE"
  reset-animation-speed: 2
  auto-reset-on-set: true
  only-reset-when-full: true
  auto-reset-on-unset-all: true

  # PREMIUM MECHANICS
  fortune-all-blocks: true
  auto-pickup-blocks: true
  notify-flight-changes: true